In [ ]:
import numpy as np


# define data table
x = np.array([1.0, 1.3, 1.6, 1.9, 2.2])
y = np.array([0.7651977, 0.6200860, 0.4554022, 0.2818186, 0.1103623])

# takes the x and y data arrays and ensures they are monotonically increasing
# this is important as bisection() only works for arrays like this
points = sorted(np.column_stack((x, y)), key=lambda p: p[0])

[array([1.       , 0.7651977]),
 array([1.3     , 0.620086]),
 array([1.6      , 0.4554022]),
 array([1.9      , 0.2818186]),
 array([2.2      , 0.1103623])]

Polynomials given by
$$
P(x) = \sum_{k = 0}^n f(x_k)L_{n,k}(x)
$$
where
$$
L_{n,k}(x) = \prod_{\substack{i = 0 \\ i \neq k}} \frac{x - x_i}{x_k - x_i}
$$

In [ ]:
def toy1DInterpolator(x, pts, k):
    # k is number of polynomials
    # find the lagrange coefficients
    l_coeff = np.zeros(k)

    for i in range(k):
        


    # find the product about

    return y


def bisection(array, value):
    '''Given an ``array`` , and given a ``value`` , returns an index j such that ``value`` is between array[j]
    and array[j+1]. ``array`` must be monotonic increasing. j=-1 or j=len(array) is returned
    to indicate that ``value`` is out of range below and above respectively.'''
    n = len(array)
    if (value < array[0]):
        return -1
    elif (value > array[n-1]):
        return n
    jl = 0                          # Initialize lower
    ju = n-1                        # and upper limits.
    while (ju-jl > 1):              # If we are not yet done,
        jm=(ju+jl) >> 1             # compute a midpoint with a bitshift
        if (value >= array[jm]):
            jl=jm                   # and replace either the lower limit
        else:
            ju=jm                   # or the upper limit, as appropriate.
                                    # Repeat until the test condition is satisfied.
    if (value == array[0]):
        return 0
    elif (value == array[n-1]):# and top
        return n-1
    else:
        return jl

1